### PR TITLE
Brownfieldland endpoints

### PR DESCRIPTION
**Pull request by kena-SL**
Ticket link - https://trello.com/c/wFlNnNHV/96-add-10-more-brownfield-land-endpoints

2 endpoints are not added in this PR as they have an SSL error and resource hash is not getting generated.

### CODE REVIEW

**Comment by mdsmith-scottlogic** [comment]
You've done the right thing excluding the SSL error endpoints, I think. Have you created another ticket to cover catching them?

**Comment by mdsmith-scottlogic** [comment]
Any idea what happened with bin/print_missing_lookups.py ?

**Comment by kena-SL** [comment]
> You've done the right thing excluding the SSL error endpoints, I think. Have you created another ticket to cover catching them?

Yes, here  https://trello.com/c/Umepxzum/246-handle-ssl-error-when-adding-brownfieldland-endpoints

**Comment by kena-SL** [comment]
> Any idea what happened with bin/print_missing_lookups.py ?

This file was not in brownfield-land-collection originally, we had to add it from article-4-direction by modifying the dataset name and resource to add.

**Review by eveleighoj — APPROVED** [review]

**Pull request merged**
